#!/bin/zsh
c=`echo 'conf\ndwm\ndwmstatus\nst\nprofile\nzshrc\nvimrc\nfehbg\nsxhkd\nxinitrc\nxresources\ndmenu\ntabbed' | dmenu -p configure: -i -l 10 $@`

if [[ $c == conf ]] ; then
	e="$EDITOR ~/.local/bin/conf"
elif [[ $c == dwm ]] ; then
	e="$EDITOR ~/.local/src/dwm/config.h && (cd ~/.local/src/dwm && make clean PREFIX=~/.local install) ; read"
elif [[ $c == dwmstatus ]] ; then
	e="$EDITOR ~/.local/bin/dwmstatus"
elif [[ $c == kshrc ]] ; then
	e="$EDITOR ~/.kshrc"
elif [[ $c == fehbg ]] ; then
	e="$EDITOR ~/.fehbg"
elif [[ $c == sxhkd ]] ; then
	e="$EDITOR ~/.config/sxhkd/sxhkdrc"
elif [[ $c == urxvt ]] ; then
	e="$EDITOR ~/.urxvt/config && xrdb ~/.Xresources ; read"
elif [[ $c == st ]] ; then
	e="$EDITOR ~/.local/src/st/config.h && (cd .local/src/st && (make clean PREFIX=~/.local TERMINFO=~/.terminfo install ; tic -sx st.info)) ; read"
elif [[ $c == profile ]] ; then
	e="$EDITOR ~/.profile"
elif [[ $c == zshrc ]] ; then
	e="$EDITOR ~/.zshrc"
elif [[ $c == xinitrc ]] ; then
	e="$EDITOR ~/.xinitrc"
elif [[ $c == xresources ]] ; then
	e="$EDITOR ~/.Xresources && xrdb ~/.Xresources ; read"
elif [[ $c == vimrc ]] ; then
	e="$EDITOR ~/.vimrc"
elif [[ $c == dmenu ]] ; then
	e="$EDITOR ~/.local/src/dmenu/config.h && (cd ~/.local/src/dmenu && make clean PREFIX=$HOME/.local install) ; read"
elif [[ $c == tabbed ]] ; then
	e="$EDITOR ~/.local/src/tabbed/config.h && (cd ~/.local/src/tabbed && make clean PREFIX=$HOME/.local install) ; read"
else
	exit 0
fi

$TERMINAL -e $SHELL -c $e
